# Automatically assigns labels to PRs based on file changes

# General Labels
'🏬 dependencies':
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'pnpm-lock.yaml'
          - 'yarn.lock'
          - 'npm-shrinkwrap.json'

'🕔 changelog':
  - changed-files:
      - any-glob-to-any-file: ['CHANGELOG.md']

#  Electron-Specific Labels
'⚡ electron-main':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/main/**'
          - 'electron/**'

'electron-renderer':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/renderer/**'
          - 'src/components/**'
          - 'src/pages/**'

# UI & Frontend
'🎨 ui':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/renderer/assets/**'
          - 'src/styles/**'
          - 'src/css/**'

# Build & Configuration
'🏗️ build':
  - changed-files:
      - any-glob-to-any-file:
          - 'webpack.config.js'
          - 'vite.config.js'
          - 'babel.config.js'
          - 'tsconfig.json'
          - 'esbuild.config.js'
          - '.eslintrc.js'
          - '.prettierrc'
          - 'scripts/**'

# Testing
'🧪 tests':
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'
          - '__tests__/**'
          - 'jest.config.js'
          - 'vitest.config.js'

# CI/CD & GitHub Actions
'🛠️ ci/cd':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/labeler.yml'

# Documentation
'📄 docs':
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - 'README.md'
          - 'CONTRIBUTING.md'
          - 'docs/**/*.md'

# Hotfix
'🔥 hotfix':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'
          - 'electron/**'
          - 'package.json'
