name: Auto-Merge Dependabot PRs

on:
  pull_request:
    branches:
      - master

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge Dependabot PR
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --auto --delete-branch
